### PR TITLE
Ember 3 and various updates

### PR DESCRIPTION
**Pull request by RobbieTheWagner**
We were getting errors with ember-cli-babel being old and deprecated. I decided to go ahead and update everything to latest standards. Please let me know if you have any questions!

### CODE REVIEW

**Comment by dnegstad** [comment]
@rwwagner90 Thanks for the pull request; I'll take a look this evening and see about getting it merged and a new version pushed up to npm. I'm pretty sure the CI tests are failing due to an outdated circle.yml file, so if everything passes locally, I can merge and make a separate update to fix that.

**Comment by RobbieTheWagner** [comment]
@dnegstad would you be opposed to just using Travis? I think everything should be setup for Travis out of the box. No worries either way, but might make things easier.

**Comment by dnegstad** [comment]
Travis works for me; I've added the repo and I'll add a build badge to the readme while I'm bumping the version number.

**Comment by dnegstad** [comment]
I just bumped the version to 2.0.0 and pushed it up to npm.

**Comment by RobbieTheWagner** [comment]
Thanks!

**Pull request merged**
